AirlineReservation/AirApp/urls.py
from django.urls import path
from . import views

app_name = "App"

urlpatterns = [
        path('', views.landing, name="Landing"),
        path('flights/', views.flight_full_list, name="FullList"),
        path('flights/add/', views.addFlight, name="AddFlight"),
        path('book/<int:flight_id>', views.bookticket, name="Booking"),
        path('data/flush', views.flush_data , name="Flush"),
        path('profile', views.profile_page, name="Profile"),
        path('cancelTicket/<int:pk>', views.cancelTicket, name="Cancellation"),
        path('deleteFlight/<int:pk>', views.deleteFlight, name="DeleteFlight"),
        path('editFlight/<int:pk>', views.editFlight, name="EditFlight"),
        path('makepayment',views.makepayment),
        path('paymentsuccess',views.paymentsuccess),
]

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns += staticfiles_urlpatterns()

AirlineReservation/AirlineReservation/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('User.urls'), name="User"),
    path('', include('AirApp.urls'), name="App")
]

AirlineReservation/User/urls.py
from django.urls import path
from . import views

app_name = 'User'

urlpatterns = [
        path('register', views.register, name="Register"),
        path('login', views.login_view , name="Login"),
        path('logout', views.logout_view, name="Logout")
]

AirlineReservation/AirApp/models.py
from django.db import models
from User.models import Passenger

locations = [
        ( 'IND', 'India' ),
        ( 'PAK', 'Pakistan' ),
        ( 'USA', 'United States'),
        ( 'GER', 'Germany'),
        ( 'FRA', 'France')
    ]


class Flight(models.Model):
    

    number = models.CharField(max_length=10, blank = False)
    source = models.CharField(max_length=10, choices = locations)
    destination = models.CharField(max_length=10, choices = locations)
    capacity = models.PositiveIntegerField()
    vacancy = models.PositiveIntegerField(blank=True,default=None)
    departure = models.DateTimeField()
    reach = models.DateTimeField()
    price_per_head = models.PositiveIntegerField()

    def vacancy_change(self, n):
        self.vacancy += n
        self.save()

    def save(self):
        if self.vacancy==None:
            self.vacancy = self.capacity
        super().save()

class Ticket(models.Model):

    passenger = models.ForeignKey(Passenger, related_name='tickets', on_delete=models.CASCADE)
    n_passenger = models.PositiveIntegerField()
    flight = models.ForeignKey(Flight, related_name='bookings',on_delete=models.CASCADE)
    number = models.CharField(max_length=10, blank = False)
    booked_at = models.DateTimeField(auto_now = True)
    totalPrice = models.PositiveIntegerField(default=0)

    def save(self):
        self.flight.vacancy_change(-self.n_passenger)
        self.totalPrice = self.flight.price_per_head * self.n_passenger
        super().save()

    def delete(self):
        self.flight.vacancy_change(self.n_passenger)
        super().delete()

AirlineReservation/templates/ConfirmationDelete.html
{% extends "Template.html" %}
{% block body_block %}

<h3> {{ message }} </h3>
<form method="POST">
	{% csrf_token %}
	<input type="submit" class="btn btn-danger" value="Yes, Delete"></input>
	<a href='{{cancelLink}}' class="btn btn-success">No, I don't</a> 
</form>

{% endblock %}

AirlineReservation/templates/FlightList.html
{% extends "Template.html" %}
{% block body_block %}
	{% if flight_list|length == 0 %}
		<div>
		<h1 style="padding-top:40px;font-family: sans-serif;"> No flights in this section </h1>
		</div>
	{% else %}
		{% for flight in flight_list %}
		<div class = "flight-div">
			<h1 style="font-family: serif; margin-top:30px;"> Flight {{ flight.number }} </h1>
			<p style="color:green; font-size: 20px;"> {{ flight.source }} to {{ flight.destination }} </p>
			<table class="table times" style="border-style: double;border-radius: 35px;border-color:white;">
				<tr>
					<td> Departure : </td>
					<td> {{flight.departure}} </td>
				</tr>
				<tr>
					<td> Reach : </td>
					<td> {{flight.reach}} </td>
				</tr>
			
			<tr> 
				<td>Vacancy: </td>
				<td>{{ flight.vacancy }} seats left out of {{ flight.capacity }}</td>
			</tr>
			<tr>
				<td> Price per head : </td>
				<td><span class="price"> Rs. {{flight.price_per_head}} </span>
				</td>
			</tr>
			</table>
			{% if user.is_superuser %}
				<a class="btn btn-danger" href="/deleteFlight/{{flight.pk}}">Delete</a>
				<a class="btn btn-primary" href="/editFlight/{{flight.pk}}">Edit</a>
			{% else %}
				{% if flight.vacancy == 0 %}
					<a class="btn btn-light">Seats Full</a>
				{% else %}
					<a href="/book/{{ flight.pk }}" class="btn btn-success">Book now</a>
				{% endif %}
			{% endif %}
		</div>
		{% endfor %}
	{% endif %}
{% endblock %}

AirlineReservation/templates/FormPage.html
{% extends "Template.html" %}
{% block body_block %}
	{% if error %}
	<div class="contaier error-block">
		<div class="alert alert-danger">
		{% if error_msg|length == 1 %}
		<h4>Error : </h4>
		{% else %}
		<h4>Errors : </h4>
		{% endif %}
			<div class="contaier error-container">
				{% for i in error_msg %}
					{{i}}<br>
				{% endfor %}
			</div>
		</div>
	</div>
	{% endif %}
	<form method="POST">
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" value="Submit"></input>
	</form>
	<script>
		$(function () {
    			$("#id_date").datetimepicker({
      				format: 'd/m/Y H:i',
    			});
    			$("#id_departure").datetimepicker({
      				format: 'd/m/Y H:i',
    			});
    			$("#id_reach").datetimepicker({
      				format: 'd/m/Y H:i',
    			});
  		});
		$(document).ready(function(){
			formClass("{{formName}}")
		});
		
	</script>
{% endblock %}

AirlineReservation/templates/MessagePage.html
{% extends "Template.html" %}
{% block body_block %}
	<h3>{{message}}</h3>
{% endblock %}

AirlineReservation/templates/ProfilePage.html
{% extends "Template.html" %}
{% block body_block %}

<h1 style="font-family: arial; margin-top: 30px;"> Your profile </h1>
<div class="userinfoblock">
	<p>
		Username : {{ passenger.user.username }}<br>
		Email : {% if passenger.email %} {{passenger.user.email}} {% else %} Not set {% endif %}
	</p>
</div>
<br>
<h3 style="font-family: georgia;">Tickets: </h3>
<hr><br>
{% if passenger.tickets.all|length %}
	{% for i in passenger.tickets.all %}
		<div class="container ticketblock">
			<h5 style="font-family: consolas;">Ticket No.  {{ i.number }}</h5>
			{{i.flight.source}} to {{i.flight.destination}} 
			<table class="table" style="border-style: double;border-radius: 35px;">
				<tr><td>Flight No.  </td><td>{{ i.flight.number }}</td></tr>
				<tr><td>Passengers  </td><td>{{ i.n_passenger }}</td></tr>
				<tr><td>Booking Time  </td><td>{{ i.booked_at }}</td></tr>
				<tr><td>Price  </td><td>{{ i.totalPrice }}</td></tr>
			</table>
			<a class="btn btn-danger" href="/cancelTicket/{{i.pk}}">Cancel</a>
		</div>
		<hr>
	{% endfor %}
{% else %}
	<h4 style="font-family: lucida console; background-color: #070707; padding: 25px; border-radius: 10px;"> No tickets booked yet...<br> Book now and let's travel!</h4>
{% endif %}

{% endblock %}

AirlineReservation/templates/Template.html
<!DOCTYPE html>
<html>
	{% load static %}
	<head>
		<title>{{title}}</title>
		<link rel="icon" href="{% static 'img/airicon.ico' %}" />
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
		<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
		<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css" integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y=" crossorigin="anonymous" />
  		<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js" integrity="sha256-FEqEelWI3WouFOo2VWP/uJfs1y8KJ++FLh2Lbqc8SJk=" crossorigin="anonymous"></script>
		<style type="text/css">
			.footer 
			{
			   	position:fixed;
			   	padding:10px;
			   	left: 0;
			   	bottom: 0;
			   	width: 100%;
			   	background-color: #000066;
			   	color: white;
			   	text-align: center;
			}

			form
			{
				opacity:1;
				margin : 0;
			}

			html,body
			{
				height:100%;
				color : white;
			}

		    	.view 
			{ 
		    		min-height: 100% 
		    	}

			.main-body-block
			{
				background-color : rgba(0,0,0,0.8);
				border-radius : 10px;
			}
			td
			{
				color : white;
			}

		</style>
  		<script src=" {% static 'js/main.js' %}" type="text/javascript"></script>
	</head>
	<body>
		{% include "navigation.html" %}
		<div class="view" style="background:url('/static/img/cloud.jpg'); background-repeat: no-repeat; background-position: center center;background-size:cover;">
		<br>
			<div class="container main-body-block">
				<br>
				{% block body_block %}
				{% endblock %}
			<br>
			</div>
			<br><br><br><br><br><br>
		</div>
		<div class="footer">
			<div class="container-fluid text-center text-md-left">
			<div class="row">
	      				<!--<div class="col-md-6 mt-md-0 mt-3">
						<h4 style="text-align: left; color:grey" class="text-uppercase font-weight-bold">Developer</h4>
        					<h5 class="text-uppercase font-weight-bold">Pratik Garai</h5>
        					<p>Collaborate with me on <a href="https://github.com/PratikGarai">https://github.com/PratikGarai</a></p>
     					</div>-->
	      				<hr class="clearfix w-100 d-md-none pb-3">
	    			</div>
  			</div>

		</div>
	</body>
</html>

AirlineReservation/templates/navigation.html
<nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #6600ff;">
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    		<span class="navbar-toggler-icon"></span>
  	</button>
  	<div class="collapse navbar-collapse" id="navbarText">
	<ul class="navbar-nav mr-auto">
		<li class="nav-item active"><a class="nav-link nav-link-custom" href = "/">Home</a></li>
		<li class="nav-item"><a class="nav-link nav-link-custom" href = '{% url "App:FullList" %}'>Full List of Flights</a></li>
		{% if user.is_superuser %}
			<li class="nav-item"><a class="nav-link nav-link-custom" href = '{% url "App:AddFlight" %}'>Add a Flight</a></li>
			<li class="nav-item"><a class="nav-link nav-link-custom" href = '{% url "App:Flush" %}'>Flush All Data</a></li>
		{% endif %}
	</ul>
	{% if user.is_authenticated %}
	<ul class="navbar-nav ml-auto nav-flex-icons">
		<li class="nav-item dropdown">
        		<a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink-333" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
	        		<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-person-circle" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  					<path d="M13.468 12.37C12.758 11.226 11.195 10 8 10s-4.757 1.225-5.468 2.37A6.987 6.987 0 0 0 8 15a6.987 6.987 0 0 0 5.468-2.63z"/>
	  				<path fill-rule="evenodd" d="M8 9a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
  					<path fill-rule="evenodd" d="M8 1a7 7 0 1 0 0 14A7 7 0 0 0 8 1zM0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8z"/>
				</svg>
        		</a>
  		      	<div class="dropdown-menu dropdown-menu-right dropdown-default" aria-labelledby="navbarDropdownMenuLink-333">
		          	<a class="dropdown-item nav-link-custom" href = '{% url  "App:Profile" %}'>View Profile</a>
          			<a class="dropdown-item nav-link-custom" href = '{% url  "User:Logout" %}'>Logout</a>
       			</div>
    		</li>
    	</ul>
	{% else %}
	<ul class="navbar-nav ml-auto nav-flex-icons">
		<li class="nav-item dropdown">
        		<a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink-333" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
		          	<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-person-circle" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  					<path d="M13.468 12.37C12.758 11.226 11.195 10 8 10s-4.757 1.225-5.468 2.37A6.987 6.987 0 0 0 8 15a6.987 6.987 0 0 0 5.468-2.63z"/>
	  				<path fill-rule="evenodd" d="M8 9a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
  					<path fill-rule="evenodd" d="M8 1a7 7 0 1 0 0 14A7 7 0 0 0 8 1zM0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8z"/>
				</svg>
		        </a>
        		<div class="dropdown-menu dropdown-menu-right dropdown-default" aria-labelledby="navbarDropdownMenuLink-333">
          			<a class="dropdown-item" href = '{% url  "User:Register" %}'>Register</a>
          			<a class="dropdown-item" href = '{% url  "User:Login" %}'>Login</a>
        		</div>
        	</li>
	</ul>			
	{% endif %}
	</div>
</nav>

AirlineReservation/templates/pay.html
{% extends "Template.html" %}
{% block body_block %}
<div class="mainContainerPage">

    <button id="rzp-button1">Pay with Razorpay</button>
    <script src="https://checkout.razorpay.com/v1/checkout.js"></script>
    <script>
        var options = {
            "key": "rzp_test_CbepQPSX6Lp3CN", // Enter the Key ID generated from the Dashboard
            "amount": "{{payment.amount}}", // Amount is in currency subunits. Default currency is INR. Hence, 50000 refers to 50000 paise
            "currency": "INR",
            "name": "Acme Corp",
            "description": "Test Transaction",
    "image": "https://example.com/your_logo",
    "order_id": "{{payment.id}}", //This is a sample Order ID. Pass the `id` obtained in the response of Step 1
    "handler": function (response){
        //alert(response.razorpay_payment_id);
        //alert(response.razorpay_order_id);
        //alert(response.razorpay_signature)
        window.location.href='/paymentsuccess'
    },
    "prefill": {
        "name": "Gaurav Kumar",
        "email": "gaurav.kumar@example.com",
        "contact": "9000090000"
    },
    "notes": {
        "address": "Razorpay Corporate Office"
    },
    "theme": {
        "color": "#3399cc"
    }
};
var rzp1 = new Razorpay(options);
rzp1.on('payment.failed', function (response){
    alert(response.error.code);
    alert(response.error.description);
    alert(response.error.source);
    alert(response.error.step);
    alert(response.error.reason);
    alert(response.error.metadata.order_id);
    alert(response.error.metadata.payment_id);
});
document.getElementById('rzp-button1').onclick = function(e){
    rzp1.open();
    e.preventDefault();
}
</script>


</div>
{% endblock %}

AirlineReservation/templates/paymentsuccess.html
{% extends "Template.html" %}
{% block body_block %}


<div class="mainContainerPage">
    <div style="margin-left: 35%;padding-top: 5%;padding-bottom: 10%;">
        <class class="row">
            <class class="col-md-6 p-3 shadow">
                <h2 class="text-success">Payment successful...!</h2><br>
                <h4>Thanks for Booking...! <h5> Visit Again </h5> </h4>
                <br>
                <a href="/" style="margin-left:30%;"><button class="btn btn-primary" type="submit"> Shop More</button></a>
            </class>
        </class>
    </div>
</div>


{% endblock %}